### ISSUE TITLE
a note for repo manager

### ISSUE THREAD

**Issue by manavbansalcoder** [DSC-COEA-Ambajogai/Hactoberfest2020#71]
sir/maam if you are reading this please define a tag hacktoberfest-accepted by looking on website as it will immidiately make our pr accepted by hactoberfest.

**Comment by manavbansalcoder** [comment]
and assign the tag to our pr it will be great help

**Comment by Dsc-coea** [comment]
Sorry for inconvenience , we will do now

**Comment by manavbansalcoder** [comment]
thanks sir
